// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiDotNetCore.Models;

namespace WebApiDotNetCore.Migrations
{
    [DbContext(typeof(WebApiDotNetCoreContext))]
    partial class WebApiDotNetCoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiDotNetCore.Models.Film", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("characters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("created")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("edited")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("episode_id")
                        .HasColumnType("int");

                    b.Property<string>("opening_crawl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("planets")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("producer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("release_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("species")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("starships")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicles")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("PK_Films");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            episode_id = 0,
                            title = "O império contra ataca"
                        },
                        new
                        {
                            ID = 2,
                            episode_id = 0,
                            title = "O ataque dos clones"
                        },
                        new
                        {
                            ID = 3,
                            episode_id = 0,
                            title = "Rogue 1"
                        });
                });

            modelBuilder.Entity("WebApiDotNetCore.Models.People", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("birth_year")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("created")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("edited")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eye_color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("films")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hair_color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("homeworld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("skin_color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("species")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("starships")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicles")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("PK_Peoples");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            name = "Luke Skywalker"
                        },
                        new
                        {
                            ID = 2,
                            name = "Anakin Skywalker"
                        },
                        new
                        {
                            ID = 3,
                            name = "Padmé Amidala"
                        });
                });

            modelBuilder.Entity("WebApiDotNetCore.Models.Planet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("climate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("created")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("diameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("edited")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("films")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gravity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("orbital_period")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("population")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("residents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rotation_period")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("surface_water")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("terrain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("PK_Planets");

                    b.ToTable("Planets");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            name = "Tatooine"
                        },
                        new
                        {
                            ID = 2,
                            name = "Hoth"
                        },
                        new
                        {
                            ID = 3,
                            name = "Mustafar"
                        });
                });

            modelBuilder.Entity("WebApiDotNetCore.Models.Root", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Films")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("People")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Planets")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Starships")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vehicles")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("PK_Root");

                    b.ToTable("Root");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Films = "https://swapi.dev/api/films/",
                            People = "https://swapi.dev/api/people/",
                            Planets = "https://swapi.dev/api/planets/",
                            Species = "https://swapi.dev/api/species/",
                            Starships = "https://swapi.dev/api/starships/",
                            Vehicles = "https://swapi.dev/api/vehicles/"
                        });
                });

            modelBuilder.Entity("WebApiDotNetCore.Models.Species", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("average_height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("average_lifespan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("classification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("created")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("edited")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eye_colors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("films")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hair_colors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("homeworld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("people")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("skin_colors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("PK_Species");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            name = "Wookie"
                        },
                        new
                        {
                            ID = 2,
                            name = "Human"
                        },
                        new
                        {
                            ID = 3,
                            name = "Clawdites"
                        });
                });

            modelBuilder.Entity("WebApiDotNetCore.Models.Starship", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MGLT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargo_capacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("consumables")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cost_in_credits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("created")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("crew")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("edited")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("films")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hyperdrive_rating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("length")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("max_atmosphering_speed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("passengers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pilots")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("starship_class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("PK_Starships");

                    b.ToTable("Starships");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            name = "Death Star"
                        },
                        new
                        {
                            ID = 2,
                            name = "Falcon"
                        },
                        new
                        {
                            ID = 3,
                            name = "Starcruiser"
                        });
                });

            modelBuilder.Entity("WebApiDotNetCore.Models.Vehicle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cargo_capacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("consumables")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cost_in_credits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("created")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("crew")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("edited")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("films")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("length")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("max_atmosphering_speed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("passengers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pilots")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicle_class")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("PK_Vehicle");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            name = "Sand Crawler"
                        },
                        new
                        {
                            ID = 2,
                            name = "X-wing"
                        },
                        new
                        {
                            ID = 3,
                            name = "Y-wing"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
